### PR TITLE
Added icons to all the dialogs

### PR DESCRIPTION
**Pull request by pandilladivya**
@AkankshaBodhankar 

image

I've put the icons on the left side of the text as shown in the mockup.
Also increased the size of the icons.

Kindly review!
Thanks :)

### CODE REVIEW

**Comment by AkankshaBodhankar** [comment]
This looks good ! Could you make the phone icon aligned with the mssg icon?

**Comment by pandilladivya** [comment]
Okay Sure!

**Comment by pandilladivya** [comment]
@AkankshaBodhankar , 

Here is the updated one!

image

I've squashed my commits.
Let me know if there are any more changes..
Thanks!

**Comment by AkankshaBodhankar** [comment]
Can you make the align center for both (icon and text). There is too much space between them and the text is getting pushed towards right side

**Comment by AkankshaBodhankar** [comment]
Also, after you are done with implementing the above changes you can ask @MeepyMay or @rosariorobinson to review and then get your code merged

**Comment by pandilladivya** [comment]
@AkankshaBodhankar , 
image

As you asked me to do,

- I've made the phone icon aligned with the message icon.

- And made the align center for both Icon and Text.

- I've put the icons on the left side of the text as shown in the mockup.

- Increased the size of the icons.

Let me know if there are any more changes..

Kindly review
@MeepyMay , @rosariorobinson , @AkankshaBodhankar 

Thank You!

**Comment by AkankshaBodhankar** [comment]
Looks great! Once @rosariorobinson and @MeepyMay review it will be ready to merge

**Comment by pandilladivya** [comment]
@AkankshaBodhankar  I didnot change anything in Readme..

I have no idea why it is showing changes :(

This is the screenshot of the current Readme in your repo
image

And this is the screenshot of my forked repo

image

both are same!

I dont know why it is showing changes...

**Comment by AkankshaBodhankar** [comment]
Try to figure out if possible

**Comment by pandilladivya** [comment]
Okay sure... will do that!

**Pull request closed without merging**
